main:
  - name: Syllabus
    url: /syllabus/
    weight: 1
  - name: Schedule
    url: /schedule/
    weight: 2
  - name: Lectures
    url: /lectures/
    weight: 4
  - name: Practicals
    url: /practicals/
    weight: 5

lectures:
  - name: Overview
    weight: 1
  - name: Course content
    weight: 2
practicals:
  - name: Overview
    weight: 1
  - name: Practicals
    weight: 2
