---
title: "Bayesian modeling"
linktitle: "Bayesian modeling"
date: "2020-06-11"
read_date: "2020-06-11"
menu:
  lectures:
    parent: "Part I: Bayesian theory"
    weight: 2
type: docs
bibliography: "../../static/bib/references.bib"
csl: "../../static/bib/chicago-fullnote-bibliography-no-bib.csl"
slides: "02-slides"
output:
  blogdown::html_page:
    toc: true
---

The **slides** for the first part of this section are displayed below, and can be downloaded [here](/slides/slidesModel1.pdf).

<iframe src="/slides/slidesModel1.pdf##view=fit" width="100%" height=450>

This browser does not support PDFs. Please download the PDF to view it: Download PDF

</iframe>


The **slides** for the second part of this section are displayed below, and can be downloaded [here](/slides/slidesModel2.pdf).

<iframe src="/slides/slidesModel2.pdf##view=fit" width="100%" height=450>

This browser does not support PDFs. Please download the PDF to view it: Download PDF

</iframe>



The **slides** for the third part of this section are displayed below, and can be downloaded [here](/slides/slidesModel3.pdf).

<iframe src="/slides/slidesModel3.pdf##view=fit" width="100%" height=450>

This browser does not support PDFs. Please download the PDF to view it: Download PDF

</iframe>



The **slides** for the fourth part of this section are displayed below, and can be downloaded [here](/slides/slidesPriors.pdf).

<iframe src="/slides/slidesPriors.pdf##view=fit" width="100%" height=450>

This browser does not support PDFs. Please download the PDF to view it: Download PDF

</iframe>



The **slides** for the fifth part of this section are displayed below, and can be downloaded [here](/slides/slidesGoingFurther.pdf).

<iframe src="/slides/slidesGoingFurther.pdf##view=fit" width="100%" height=450>

This browser does not support PDFs. Please download the PDF to view it: Download PDF

</iframe>